server:
  port: 8092
  servlet:
    context-path: /jm-hxsq

spring:
  profiles:
    active: dev
  application:
    name: jm-hxsq

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true